FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm run build

ENV NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCtRQpJ-d3ubE4Nv8xvDXFWTDJ111J0LfI
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=dzencodetz.firebaseapp.com
ENV NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://dzencodetz-default-rtdb.firebaseio.com
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=dzencodetz
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=dzencodetz.firebasestorage.app
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=698242574752
ENV NEXT_PUBLIC_FIREBASE_APP_ID=1:698242574752:web:482ddc9049c4e5a84f1cc5
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-WYGM3FY17M

EXPOSE 3000

CMD ["npm", "run", "start"]
